### ISSUE TITLE
code 35072 Too big a dataset?

### ISSUE THREAD

**Issue by Bavar2142** [pierotofy/node-OpenDroneMap#13]
Was testing out Node yesterday with an existing data set whose output via open drone map was known and got the below error. Could it be because the data set was too large?

[ERROR]   quitting cause: 
	/code/SuperBuild/install/bin/pmvs2 /var/www/data/935daf41-22d0-4163-86bf-734803e633f5/pmvs/recon0/ option-0000
returned with code 35072.

**Comment by pierotofy** [comment]
Could be, see. https://github.com/OpenDroneMap/OpenDroneMap/issues/28

How many images were you trying to process? What were the machine specs and environment?

Try to reduce the **resize-to** and/or the **min-num-features** options.

**Comment by Bavar2142** [comment]
It worked with 16 and then failed with 40, 60 and 150 images.

**Comment by Bavar2142** [comment]
Will try again with those parameters reduced by 50%

**Comment by Bavar2142** [comment]
That worked. I was able to get it to work at 75% of the default settings.
