### ISSUE TITLE
Use swagger

### ISSUE THREAD

**Issue by matthewberryman** [pierotofy/node-OpenDroneMap#2]
Hi,

Just a suggestion to use swagger for defining the API. This helps with both documentation, unit testing, and you can also auto-generate node.js templates from swagger. At the moment, because you have existing APIs defined, you would need to reverse engineer the API from your index.js file, using swagger-jsdoc, and I have made a start on this here https://github.com/smart-facility/node-OpenDroneMap/tree/swagger , notably [index.js#L163](https://github.com/smart-facility/node-OpenDroneMap/blob/swagger/index.js#L163) has the first swagger js doc comments (in swagger YAML, with js commenting), and [generateSwaggerAPI.js](https://github.com/smart-facility/node-OpenDroneMap/blob/swagger/generateSwaggerAPI.js) will take index.js and generate the json API document [swagger-api.json](https://github.com/smart-facility/node-OpenDroneMap/blob/swagger/swagger-api.json)

Another advantage of swagger is if you do go to a "serverless" model (AWS Lambda or similar microservice behind an API gateway service) then it helps set up your APIs and associated microservices there (my own example at https://github.com/matthewberryman/brunsviga as running at [brunsviga.io](https://brunsviga.io) ). 

Let me know your thoughts.

Cheers,
Matthew

**Comment by pierotofy** [comment]
I was eventually planning to use a tool like swagger for defining the API, but I'm glad you went ahead! So yes, I think it would be a good choice!

**Comment by matthewberryman** [comment]
Ok. I will reverse engineer as much of the swagger jsdocs as I can from your code, and then submit a pull request in due course* and you can review and then complete the work.

* I have lots of travel coming up but will squeeze in some steady work on node-OpenDroneMap.

**Comment by pierotofy** [comment]
Sounds good! :+1:

**Comment by pierotofy** [comment]
I'm going to work on this one, if that's all right?

**Comment by matthewberryman** [comment]
Yes, good, as I've still been somewhat busy, but also best if this comes from you, as you have already written the API calls.

**Comment by pierotofy** [comment]
@matthewberryman do you know of a good editor for creating swagger YAML definitions? The one here editor.swagger.io is kind of picky and not helpful at all when troubleshooting messages.

**Comment by pierotofy** [comment]
Done! API docs are here: https://github.com/pierotofy/node-OpenDroneMap/blob/master/docs/index.adoc

Swagger definition file is here: https://github.com/pierotofy/node-OpenDroneMap/blob/master/docs/swagger.json

**Comment by matthewberryman** [comment]
@pierotofy Good work! I've not used that swagger editor; I'm still a bit new, and my previous use of swagger was actually as an exported example from the API builder UI in AWS API gateway, plus a little by hand in YML as done on node-ODM previously.
