### ISSUE TITLE
How send images through the REST api? 

### ISSUE THREAD

**Issue by Cardoso222** [pierotofy/node-OpenDroneMap#8]
I'm using the POST route `/task/new` and receiving this message:

 
![captura de tela 2017-12-24 as 11 09 29](https://user-images.githubusercontent.com/7026517/34327108-f4dc682c-e89a-11e7-996e-faf233019468.png)

additional info:
```json
"headers": { 
  "Content-Type": "application/json"
}
```

**Comment by pierotofy** [comment]
Hey @Cardoso222, make sure you are passing the `images` or `zipurl` parameter to /task/new. https://github.com/OpenDroneMap/node-OpenDroneMap/blob/master/docs/index.adoc#post-tasknew

**Comment by Cardoso222** [comment]
thanks for answering me so fast! 
i'm passing `images` and the images files as a value. look:
![captura de tela 2017-12-24 as 11 27 57](https://user-images.githubusercontent.com/7026517/34327217-8dac6f64-e89d-11e7-9b95-e1e223452e8a.png)

**Comment by pierotofy** [comment]
Mm, I just sent a request and it worked fine.

![image](https://user-images.githubusercontent.com/1951843/34328068-df13f502-e8a2-11e7-9e8d-c192c54ea054.png)

Did you correctly setup OpenDroneMap before attempting to run node-OpenDroneMap? I highly recommend using docker for running node-OpenDroneMap, if you're attempting to set it up natively make sure follow the README instructions carefully.

**Comment by Cardoso222** [comment]
Problem solved! I just remove my headers `content-type` ( i saw on your print screen ). Thanks!
